# Generated by Django 4.2.5 on 2024-05-29 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intSocial', '0011_alter_post_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('genero_preferido', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=20)),
                ('personalidad', models.CharField(max_length=20)),
                ('paz_interior', models.CharField(max_length=20)),
                ('sueño', models.CharField(max_length=50)),
                ('tiempo_de_juego', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=20)),
                ('dias_de_juego', models.CharField(max_length=20)),
                ('escuchas_musica_mientras_juegas', models.CharField(max_length=10)),
                ('enfoque_de_juego', models.CharField(max_length=20)),
                ('plataforma_preferida', models.CharField(max_length=20)),
                ('comunicacion', models.CharField(max_length=20)),
                ('modalidad_de_juego', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
