# Generated by Django 4.2.5 on 2024-05-30 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intSocial', '0012_encuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta_peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_peso', models.FloatField(default=0)),
                ('sexo_peso', models.FloatField(default=0)),
                ('genero_preferido_peso', models.FloatField(default=0)),
                ('ocupacion_peso', models.FloatField(default=0)),
                ('personalidad_peso', models.FloatField(default=0)),
                ('paz_interior_peso', models.FloatField(default=0)),
                ('sueño_peso', models.FloatField(default=0)),
                ('tiempo_de_juego_peso', models.FloatField(default=0)),
                ('horario_peso', models.FloatField(default=0)),
                ('dias_de_juego_peso', models.FloatField(default=0)),
                ('escuchas_musica_mientras_juegas_peso', models.FloatField(default=0)),
                ('enfoque_de_juego_peso', models.FloatField(default=0)),
                ('plataforma_preferida_peso', models.FloatField(default=0)),
                ('comunicacion_peso', models.FloatField(default=0)),
                ('modalidad_de_juego_peso', models.FloatField(default=0)),
                ('total_pesos', models.FloatField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
